# Generated by Django 5.2.5 on 2025-08-28 11:05

import django.db.models.deletion
import drf_role.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_role', '0002_alter_accesscontrol_id_alter_permission_id_and_more'),
        ('email_login', '0003_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(default=drf_role.enums.RoleEnum['Buyer'], on_delete=django.db.models.deletion.CASCADE, to='drf_role.role'),
        ),
    ]
